// @generated by protobuf-ts 2.11.1 with parameter long_type_string,generate_dependencies,output_typescript,client_grpc1,server_grpc1
// @generated from protobuf file "steam/steam.proto" (package "steam", syntax proto3)
// tslint:disable
import { GetCaseWhitelistResponse } from "./steam";
import { GetCaseWhitelistRequest } from "./steam";
import { ValidateTradeUrlResponse } from "./steam";
import { ValidateTradeUrlRequest } from "./steam";
import { CancelTradeOfferResponse } from "./steam";
import { CancelTradeOfferRequest } from "./steam";
import { GetTradeOfferStatusResponse } from "./steam";
import { GetTradeOfferStatusRequest } from "./steam";
import { SendTradeOfferResponse } from "./steam";
import { SendTradeOfferRequest } from "./steam";
import { GetBotInventoryResponse } from "./steam";
import { GetBotInventoryRequest } from "./steam";
import { GetInventoryResponse } from "./steam";
import { GetInventoryRequest } from "./steam";
import { GetProfileResponse } from "./steam";
import { GetProfileRequest } from "./steam";
import type * as grpc from "@grpc/grpc-js";
// ============================================================================
// Service
// ============================================================================

/**
 * @generated from protobuf service steam.SteamService
 */
export interface ISteamService extends grpc.UntypedServiceImplementation {
    /**
     * Profile operations
     *
     * @generated from protobuf rpc: GetProfile
     */
    getProfile: grpc.handleUnaryCall<GetProfileRequest, GetProfileResponse>;
    /**
     * Inventory operations
     *
     * @generated from protobuf rpc: GetInventory
     */
    getInventory: grpc.handleUnaryCall<GetInventoryRequest, GetInventoryResponse>;
    /**
     * @generated from protobuf rpc: GetBotInventory
     */
    getBotInventory: grpc.handleUnaryCall<GetBotInventoryRequest, GetBotInventoryResponse>;
    /**
     * Trade operations
     *
     * @generated from protobuf rpc: SendTradeOffer
     */
    sendTradeOffer: grpc.handleUnaryCall<SendTradeOfferRequest, SendTradeOfferResponse>;
    /**
     * @generated from protobuf rpc: GetTradeOfferStatus
     */
    getTradeOfferStatus: grpc.handleUnaryCall<GetTradeOfferStatusRequest, GetTradeOfferStatusResponse>;
    /**
     * @generated from protobuf rpc: CancelTradeOffer
     */
    cancelTradeOffer: grpc.handleUnaryCall<CancelTradeOfferRequest, CancelTradeOfferResponse>;
    /**
     * Validation
     *
     * @generated from protobuf rpc: ValidateTradeUrl
     */
    validateTradeUrl: grpc.handleUnaryCall<ValidateTradeUrlRequest, ValidateTradeUrlResponse>;
    /**
     * @generated from protobuf rpc: GetCaseWhitelist
     */
    getCaseWhitelist: grpc.handleUnaryCall<GetCaseWhitelistRequest, GetCaseWhitelistResponse>;
}
/**
 * @grpc/grpc-js definition for the protobuf service steam.SteamService.
 *
 * Usage: Implement the interface ISteamService and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: ISteamService = ...
 * server.addService(steamServiceDefinition, service);
 * ```
 */
export const steamServiceDefinition: grpc.ServiceDefinition<ISteamService> = {
    getProfile: {
        path: "/steam.SteamService/GetProfile",
        originalName: "GetProfile",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetProfileResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetProfileRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetProfileResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetProfileRequest.toBinary(value))
    },
    getInventory: {
        path: "/steam.SteamService/GetInventory",
        originalName: "GetInventory",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetInventoryResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetInventoryRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetInventoryResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetInventoryRequest.toBinary(value))
    },
    getBotInventory: {
        path: "/steam.SteamService/GetBotInventory",
        originalName: "GetBotInventory",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetBotInventoryResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetBotInventoryRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetBotInventoryResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetBotInventoryRequest.toBinary(value))
    },
    sendTradeOffer: {
        path: "/steam.SteamService/SendTradeOffer",
        originalName: "SendTradeOffer",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => SendTradeOfferResponse.fromBinary(bytes),
        requestDeserialize: bytes => SendTradeOfferRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(SendTradeOfferResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(SendTradeOfferRequest.toBinary(value))
    },
    getTradeOfferStatus: {
        path: "/steam.SteamService/GetTradeOfferStatus",
        originalName: "GetTradeOfferStatus",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetTradeOfferStatusResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetTradeOfferStatusRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetTradeOfferStatusResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetTradeOfferStatusRequest.toBinary(value))
    },
    cancelTradeOffer: {
        path: "/steam.SteamService/CancelTradeOffer",
        originalName: "CancelTradeOffer",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => CancelTradeOfferResponse.fromBinary(bytes),
        requestDeserialize: bytes => CancelTradeOfferRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(CancelTradeOfferResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(CancelTradeOfferRequest.toBinary(value))
    },
    validateTradeUrl: {
        path: "/steam.SteamService/ValidateTradeUrl",
        originalName: "ValidateTradeUrl",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => ValidateTradeUrlResponse.fromBinary(bytes),
        requestDeserialize: bytes => ValidateTradeUrlRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(ValidateTradeUrlResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(ValidateTradeUrlRequest.toBinary(value))
    },
    getCaseWhitelist: {
        path: "/steam.SteamService/GetCaseWhitelist",
        originalName: "GetCaseWhitelist",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetCaseWhitelistResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetCaseWhitelistRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetCaseWhitelistResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetCaseWhitelistRequest.toBinary(value))
    }
};
