// @generated by protobuf-ts 2.11.1 with parameter long_type_string,generate_dependencies,output_typescript,client_grpc1,server_grpc1
// @generated from protobuf file "steam/steam.proto" (package "steam", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// ============================================================================
// Messages
// ============================================================================

/**
 * @generated from protobuf message steam.SteamProfile
 */
export interface SteamProfile {
    /**
     * @generated from protobuf field: string steam_id = 1
     */
    steamId: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string avatar_hash = 3
     */
    avatarHash: string;
    /**
     * @generated from protobuf field: string privacy_state = 4
     */
    privacyState: string; // "public", "private", "friendsonly"
    /**
     * @generated from protobuf field: string visibility_state = 5
     */
    visibilityState: string;
    /**
     * @generated from protobuf field: bool vac_banned = 6
     */
    vacBanned: boolean;
    /**
     * @generated from protobuf field: string trade_ban_state = 7
     */
    tradeBanState: string;
    /**
     * @generated from protobuf field: bool is_limited_account = 8
     */
    isLimitedAccount: boolean;
    /**
     * @generated from protobuf field: string custom_url = 9
     */
    customUrl: string;
    /**
     * @generated from protobuf field: string real_name = 10
     */
    realName: string;
    /**
     * @generated from protobuf field: string location = 11
     */
    location: string;
    /**
     * @generated from protobuf field: string online_state = 12
     */
    onlineState: string;
    /**
     * @generated from protobuf field: string state_message = 13
     */
    stateMessage: string;
    /**
     * @generated from protobuf field: string summary = 14
     */
    summary: string;
    /**
     * @generated from protobuf field: string member_since = 15
     */
    memberSince: string; // ISO timestamp
}
/**
 * @generated from protobuf message steam.InventoryItem
 */
export interface InventoryItem {
    /**
     * @generated from protobuf field: string asset_id = 1
     */
    assetId: string;
    /**
     * @generated from protobuf field: string class_id = 2
     */
    classId: string;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: bool tradable = 4
     */
    tradable: boolean;
    /**
     * @generated from protobuf field: string icon_url = 5
     */
    iconUrl: string;
    /**
     * @generated from protobuf field: string quality = 6
     */
    quality: string;
    /**
     * @generated from protobuf field: string rarity = 7
     */
    rarity: string;
    /**
     * @generated from protobuf field: bool is_case = 8
     */
    isCase: boolean; // Validated against whitelist
}
/**
 * @generated from protobuf message steam.InventoryAsset
 */
export interface InventoryAsset {
    /**
     * @generated from protobuf field: int32 app_id = 1
     */
    appId: number; // Always 730 for CS2
    /**
     * @generated from protobuf field: string context_id = 2
     */
    contextId: string; // Always "2" for CS2
    /**
     * @generated from protobuf field: string asset_id = 3
     */
    assetId: string;
}
/**
 * @generated from protobuf message steam.TradeOffer
 */
export interface TradeOffer {
    /**
     * @generated from protobuf field: string offer_id = 1
     */
    offerId: string;
    /**
     * @generated from protobuf field: string status = 2
     */
    status: string; // "pending", "accepted", "declined", "cancelled", "expired", "invalid"
    /**
     * @generated from protobuf field: repeated steam.InventoryAsset items_to_receive = 3
     */
    itemsToReceive: InventoryAsset[];
    /**
     * @generated from protobuf field: repeated steam.InventoryAsset items_to_give = 4
     */
    itemsToGive: InventoryAsset[];
    /**
     * @generated from protobuf field: string created_at = 5
     */
    createdAt: string; // ISO timestamp
    /**
     * @generated from protobuf field: string updated_at = 6
     */
    updatedAt: string; // ISO timestamp
}
/**
 * @generated from protobuf message steam.CaseInfo
 */
export interface CaseInfo {
    /**
     * @generated from protobuf field: string class_id = 1
     */
    classId: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string icon_url = 3
     */
    iconUrl: string;
}
// ============================================================================
// Requests / Responses
// ============================================================================

/**
 * GetProfile
 *
 * @generated from protobuf message steam.GetProfileRequest
 */
export interface GetProfileRequest {
    /**
     * @generated from protobuf field: string steam_id = 1
     */
    steamId: string;
}
/**
 * @generated from protobuf message steam.GetProfileResponse
 */
export interface GetProfileResponse {
    /**
     * @generated from protobuf field: steam.SteamProfile profile = 1
     */
    profile?: SteamProfile;
    /**
     * @generated from protobuf field: bool from_cache = 2
     */
    fromCache: boolean;
    /**
     * @generated from protobuf field: string error = 3
     */
    error: string; // "not_found", "private", "rate_limited"
}
/**
 * GetInventory
 *
 * @generated from protobuf message steam.GetInventoryRequest
 */
export interface GetInventoryRequest {
    /**
     * @generated from protobuf field: string steam_id = 1
     */
    steamId: string;
    /**
     * @generated from protobuf field: bool cases_only = 2
     */
    casesOnly: boolean; // Filter to only cases
}
/**
 * @generated from protobuf message steam.GetInventoryResponse
 */
export interface GetInventoryResponse {
    /**
     * @generated from protobuf field: repeated steam.InventoryItem items = 1
     */
    items: InventoryItem[];
    /**
     * @generated from protobuf field: bool from_cache = 2
     */
    fromCache: boolean;
    /**
     * @generated from protobuf field: string error = 3
     */
    error: string; // "private", "rate_limited", "not_found"
}
/**
 * SendTradeOffer
 *
 * @generated from protobuf message steam.SendTradeOfferRequest
 */
export interface SendTradeOfferRequest {
    /**
     * @generated from protobuf field: string trade_url = 1
     */
    tradeUrl: string;
    /**
     * @generated from protobuf field: repeated steam.InventoryAsset their_items = 2
     */
    theirItems: InventoryAsset[]; // Items to receive from user
    /**
     * @generated from protobuf field: repeated steam.InventoryAsset our_items = 3
     */
    ourItems: InventoryAsset[]; // Items to send to user (payouts)
    /**
     * @generated from protobuf field: string message = 4
     */
    message: string;
}
/**
 * @generated from protobuf message steam.SendTradeOfferResponse
 */
export interface SendTradeOfferResponse {
    /**
     * @generated from protobuf field: string offer_id = 1
     */
    offerId: string;
    /**
     * @generated from protobuf field: string status = 2
     */
    status: string; // "pending", "sent", "error"
    /**
     * @generated from protobuf field: string error = 3
     */
    error: string; // Error message if failed
}
/**
 * GetTradeOfferStatus
 *
 * @generated from protobuf message steam.GetTradeOfferStatusRequest
 */
export interface GetTradeOfferStatusRequest {
    /**
     * @generated from protobuf field: string offer_id = 1
     */
    offerId: string;
}
/**
 * @generated from protobuf message steam.GetTradeOfferStatusResponse
 */
export interface GetTradeOfferStatusResponse {
    /**
     * @generated from protobuf field: string offer_id = 1
     */
    offerId: string;
    /**
     * @generated from protobuf field: string status = 2
     */
    status: string; // "pending", "accepted", "declined", "cancelled", "expired", "invalid"
    /**
     * @generated from protobuf field: repeated steam.InventoryAsset received_items = 3
     */
    receivedItems: InventoryAsset[]; // Items received (if accepted)
    /**
     * @generated from protobuf field: string error = 4
     */
    error: string;
}
/**
 * CancelTradeOffer
 *
 * @generated from protobuf message steam.CancelTradeOfferRequest
 */
export interface CancelTradeOfferRequest {
    /**
     * @generated from protobuf field: string offer_id = 1
     */
    offerId: string;
}
/**
 * @generated from protobuf message steam.CancelTradeOfferResponse
 */
export interface CancelTradeOfferResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string error = 2
     */
    error: string;
}
/**
 * GetCaseWhitelist
 *
 * @generated from protobuf message steam.GetCaseWhitelistRequest
 */
export interface GetCaseWhitelistRequest {
}
/**
 * @generated from protobuf message steam.GetCaseWhitelistResponse
 */
export interface GetCaseWhitelistResponse {
    /**
     * @generated from protobuf field: repeated steam.CaseInfo cases = 1
     */
    cases: CaseInfo[];
}
/**
 * ValidateTradeUrl
 *
 * @generated from protobuf message steam.ValidateTradeUrlRequest
 */
export interface ValidateTradeUrlRequest {
    /**
     * @generated from protobuf field: string trade_url = 1
     */
    tradeUrl: string;
    /**
     * @generated from protobuf field: string steam_id = 2
     */
    steamId: string; // Expected steam ID (for partner validation)
}
/**
 * @generated from protobuf message steam.ValidateTradeUrlResponse
 */
export interface ValidateTradeUrlResponse {
    /**
     * @generated from protobuf field: bool valid = 1
     */
    valid: boolean;
    /**
     * @generated from protobuf field: string partner_id = 2
     */
    partnerId: string; // Extracted partner ID from URL
    /**
     * @generated from protobuf field: string error = 3
     */
    error: string; // "invalid_format", "partner_mismatch", "invalid_token"
}
/**
 * GetBotInventory - get the pool bot's inventory
 *
 * @generated from protobuf message steam.GetBotInventoryRequest
 */
export interface GetBotInventoryRequest {
    /**
     * @generated from protobuf field: bool cases_only = 1
     */
    casesOnly: boolean;
}
/**
 * @generated from protobuf message steam.GetBotInventoryResponse
 */
export interface GetBotInventoryResponse {
    /**
     * @generated from protobuf field: repeated steam.InventoryItem items = 1
     */
    items: InventoryItem[];
    /**
     * @generated from protobuf field: string error = 2
     */
    error: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class SteamProfile$Type extends MessageType<SteamProfile> {
    constructor() {
        super("steam.SteamProfile", [
            { no: 1, name: "steam_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "avatar_hash", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "privacy_state", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "visibility_state", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "vac_banned", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "trade_ban_state", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "is_limited_account", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 9, name: "custom_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "real_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "location", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "online_state", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "state_message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "summary", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "member_since", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SteamProfile>): SteamProfile {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.steamId = "";
        message.name = "";
        message.avatarHash = "";
        message.privacyState = "";
        message.visibilityState = "";
        message.vacBanned = false;
        message.tradeBanState = "";
        message.isLimitedAccount = false;
        message.customUrl = "";
        message.realName = "";
        message.location = "";
        message.onlineState = "";
        message.stateMessage = "";
        message.summary = "";
        message.memberSince = "";
        if (value !== undefined)
            reflectionMergePartial<SteamProfile>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SteamProfile): SteamProfile {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string steam_id */ 1:
                    message.steamId = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string avatar_hash */ 3:
                    message.avatarHash = reader.string();
                    break;
                case /* string privacy_state */ 4:
                    message.privacyState = reader.string();
                    break;
                case /* string visibility_state */ 5:
                    message.visibilityState = reader.string();
                    break;
                case /* bool vac_banned */ 6:
                    message.vacBanned = reader.bool();
                    break;
                case /* string trade_ban_state */ 7:
                    message.tradeBanState = reader.string();
                    break;
                case /* bool is_limited_account */ 8:
                    message.isLimitedAccount = reader.bool();
                    break;
                case /* string custom_url */ 9:
                    message.customUrl = reader.string();
                    break;
                case /* string real_name */ 10:
                    message.realName = reader.string();
                    break;
                case /* string location */ 11:
                    message.location = reader.string();
                    break;
                case /* string online_state */ 12:
                    message.onlineState = reader.string();
                    break;
                case /* string state_message */ 13:
                    message.stateMessage = reader.string();
                    break;
                case /* string summary */ 14:
                    message.summary = reader.string();
                    break;
                case /* string member_since */ 15:
                    message.memberSince = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SteamProfile, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string steam_id = 1; */
        if (message.steamId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.steamId);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string avatar_hash = 3; */
        if (message.avatarHash !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.avatarHash);
        /* string privacy_state = 4; */
        if (message.privacyState !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.privacyState);
        /* string visibility_state = 5; */
        if (message.visibilityState !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.visibilityState);
        /* bool vac_banned = 6; */
        if (message.vacBanned !== false)
            writer.tag(6, WireType.Varint).bool(message.vacBanned);
        /* string trade_ban_state = 7; */
        if (message.tradeBanState !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.tradeBanState);
        /* bool is_limited_account = 8; */
        if (message.isLimitedAccount !== false)
            writer.tag(8, WireType.Varint).bool(message.isLimitedAccount);
        /* string custom_url = 9; */
        if (message.customUrl !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.customUrl);
        /* string real_name = 10; */
        if (message.realName !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.realName);
        /* string location = 11; */
        if (message.location !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.location);
        /* string online_state = 12; */
        if (message.onlineState !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.onlineState);
        /* string state_message = 13; */
        if (message.stateMessage !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.stateMessage);
        /* string summary = 14; */
        if (message.summary !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.summary);
        /* string member_since = 15; */
        if (message.memberSince !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.memberSince);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.SteamProfile
 */
export const SteamProfile = new SteamProfile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InventoryItem$Type extends MessageType<InventoryItem> {
    constructor() {
        super("steam.InventoryItem", [
            { no: 1, name: "asset_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "class_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "tradable", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "icon_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "quality", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "rarity", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "is_case", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<InventoryItem>): InventoryItem {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.assetId = "";
        message.classId = "";
        message.name = "";
        message.tradable = false;
        message.iconUrl = "";
        message.quality = "";
        message.rarity = "";
        message.isCase = false;
        if (value !== undefined)
            reflectionMergePartial<InventoryItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InventoryItem): InventoryItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string asset_id */ 1:
                    message.assetId = reader.string();
                    break;
                case /* string class_id */ 2:
                    message.classId = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* bool tradable */ 4:
                    message.tradable = reader.bool();
                    break;
                case /* string icon_url */ 5:
                    message.iconUrl = reader.string();
                    break;
                case /* string quality */ 6:
                    message.quality = reader.string();
                    break;
                case /* string rarity */ 7:
                    message.rarity = reader.string();
                    break;
                case /* bool is_case */ 8:
                    message.isCase = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InventoryItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string asset_id = 1; */
        if (message.assetId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.assetId);
        /* string class_id = 2; */
        if (message.classId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.classId);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* bool tradable = 4; */
        if (message.tradable !== false)
            writer.tag(4, WireType.Varint).bool(message.tradable);
        /* string icon_url = 5; */
        if (message.iconUrl !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.iconUrl);
        /* string quality = 6; */
        if (message.quality !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.quality);
        /* string rarity = 7; */
        if (message.rarity !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.rarity);
        /* bool is_case = 8; */
        if (message.isCase !== false)
            writer.tag(8, WireType.Varint).bool(message.isCase);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.InventoryItem
 */
export const InventoryItem = new InventoryItem$Type();
// @generated message type with reflection information, may provide speed optimized methods
class InventoryAsset$Type extends MessageType<InventoryAsset> {
    constructor() {
        super("steam.InventoryAsset", [
            { no: 1, name: "app_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "context_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "asset_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<InventoryAsset>): InventoryAsset {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.appId = 0;
        message.contextId = "";
        message.assetId = "";
        if (value !== undefined)
            reflectionMergePartial<InventoryAsset>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: InventoryAsset): InventoryAsset {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 app_id */ 1:
                    message.appId = reader.int32();
                    break;
                case /* string context_id */ 2:
                    message.contextId = reader.string();
                    break;
                case /* string asset_id */ 3:
                    message.assetId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: InventoryAsset, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 app_id = 1; */
        if (message.appId !== 0)
            writer.tag(1, WireType.Varint).int32(message.appId);
        /* string context_id = 2; */
        if (message.contextId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.contextId);
        /* string asset_id = 3; */
        if (message.assetId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.assetId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.InventoryAsset
 */
export const InventoryAsset = new InventoryAsset$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TradeOffer$Type extends MessageType<TradeOffer> {
    constructor() {
        super("steam.TradeOffer", [
            { no: 1, name: "offer_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "items_to_receive", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => InventoryAsset },
            { no: 4, name: "items_to_give", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => InventoryAsset },
            { no: 5, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TradeOffer>): TradeOffer {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.offerId = "";
        message.status = "";
        message.itemsToReceive = [];
        message.itemsToGive = [];
        message.createdAt = "";
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<TradeOffer>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TradeOffer): TradeOffer {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string offer_id */ 1:
                    message.offerId = reader.string();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                case /* repeated steam.InventoryAsset items_to_receive */ 3:
                    message.itemsToReceive.push(InventoryAsset.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated steam.InventoryAsset items_to_give */ 4:
                    message.itemsToGive.push(InventoryAsset.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string created_at */ 5:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 6:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TradeOffer, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string offer_id = 1; */
        if (message.offerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.offerId);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        /* repeated steam.InventoryAsset items_to_receive = 3; */
        for (let i = 0; i < message.itemsToReceive.length; i++)
            InventoryAsset.internalBinaryWrite(message.itemsToReceive[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated steam.InventoryAsset items_to_give = 4; */
        for (let i = 0; i < message.itemsToGive.length; i++)
            InventoryAsset.internalBinaryWrite(message.itemsToGive[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string created_at = 5; */
        if (message.createdAt !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 6; */
        if (message.updatedAt !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.TradeOffer
 */
export const TradeOffer = new TradeOffer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CaseInfo$Type extends MessageType<CaseInfo> {
    constructor() {
        super("steam.CaseInfo", [
            { no: 1, name: "class_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "icon_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CaseInfo>): CaseInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.classId = "";
        message.name = "";
        message.iconUrl = "";
        if (value !== undefined)
            reflectionMergePartial<CaseInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CaseInfo): CaseInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string class_id */ 1:
                    message.classId = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string icon_url */ 3:
                    message.iconUrl = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CaseInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string class_id = 1; */
        if (message.classId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.classId);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string icon_url = 3; */
        if (message.iconUrl !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.iconUrl);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.CaseInfo
 */
export const CaseInfo = new CaseInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetProfileRequest$Type extends MessageType<GetProfileRequest> {
    constructor() {
        super("steam.GetProfileRequest", [
            { no: 1, name: "steam_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetProfileRequest>): GetProfileRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.steamId = "";
        if (value !== undefined)
            reflectionMergePartial<GetProfileRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetProfileRequest): GetProfileRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string steam_id */ 1:
                    message.steamId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetProfileRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string steam_id = 1; */
        if (message.steamId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.steamId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.GetProfileRequest
 */
export const GetProfileRequest = new GetProfileRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetProfileResponse$Type extends MessageType<GetProfileResponse> {
    constructor() {
        super("steam.GetProfileResponse", [
            { no: 1, name: "profile", kind: "message", T: () => SteamProfile },
            { no: 2, name: "from_cache", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetProfileResponse>): GetProfileResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fromCache = false;
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<GetProfileResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetProfileResponse): GetProfileResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* steam.SteamProfile profile */ 1:
                    message.profile = SteamProfile.internalBinaryRead(reader, reader.uint32(), options, message.profile);
                    break;
                case /* bool from_cache */ 2:
                    message.fromCache = reader.bool();
                    break;
                case /* string error */ 3:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetProfileResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* steam.SteamProfile profile = 1; */
        if (message.profile)
            SteamProfile.internalBinaryWrite(message.profile, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool from_cache = 2; */
        if (message.fromCache !== false)
            writer.tag(2, WireType.Varint).bool(message.fromCache);
        /* string error = 3; */
        if (message.error !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.GetProfileResponse
 */
export const GetProfileResponse = new GetProfileResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetInventoryRequest$Type extends MessageType<GetInventoryRequest> {
    constructor() {
        super("steam.GetInventoryRequest", [
            { no: 1, name: "steam_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "cases_only", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<GetInventoryRequest>): GetInventoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.steamId = "";
        message.casesOnly = false;
        if (value !== undefined)
            reflectionMergePartial<GetInventoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetInventoryRequest): GetInventoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string steam_id */ 1:
                    message.steamId = reader.string();
                    break;
                case /* bool cases_only */ 2:
                    message.casesOnly = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetInventoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string steam_id = 1; */
        if (message.steamId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.steamId);
        /* bool cases_only = 2; */
        if (message.casesOnly !== false)
            writer.tag(2, WireType.Varint).bool(message.casesOnly);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.GetInventoryRequest
 */
export const GetInventoryRequest = new GetInventoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetInventoryResponse$Type extends MessageType<GetInventoryResponse> {
    constructor() {
        super("steam.GetInventoryResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => InventoryItem },
            { no: 2, name: "from_cache", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetInventoryResponse>): GetInventoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        message.fromCache = false;
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<GetInventoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetInventoryResponse): GetInventoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated steam.InventoryItem items */ 1:
                    message.items.push(InventoryItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool from_cache */ 2:
                    message.fromCache = reader.bool();
                    break;
                case /* string error */ 3:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetInventoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated steam.InventoryItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            InventoryItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool from_cache = 2; */
        if (message.fromCache !== false)
            writer.tag(2, WireType.Varint).bool(message.fromCache);
        /* string error = 3; */
        if (message.error !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.GetInventoryResponse
 */
export const GetInventoryResponse = new GetInventoryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendTradeOfferRequest$Type extends MessageType<SendTradeOfferRequest> {
    constructor() {
        super("steam.SendTradeOfferRequest", [
            { no: 1, name: "trade_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "their_items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => InventoryAsset },
            { no: 3, name: "our_items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => InventoryAsset },
            { no: 4, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SendTradeOfferRequest>): SendTradeOfferRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tradeUrl = "";
        message.theirItems = [];
        message.ourItems = [];
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<SendTradeOfferRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendTradeOfferRequest): SendTradeOfferRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string trade_url */ 1:
                    message.tradeUrl = reader.string();
                    break;
                case /* repeated steam.InventoryAsset their_items */ 2:
                    message.theirItems.push(InventoryAsset.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated steam.InventoryAsset our_items */ 3:
                    message.ourItems.push(InventoryAsset.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string message */ 4:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendTradeOfferRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string trade_url = 1; */
        if (message.tradeUrl !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tradeUrl);
        /* repeated steam.InventoryAsset their_items = 2; */
        for (let i = 0; i < message.theirItems.length; i++)
            InventoryAsset.internalBinaryWrite(message.theirItems[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated steam.InventoryAsset our_items = 3; */
        for (let i = 0; i < message.ourItems.length; i++)
            InventoryAsset.internalBinaryWrite(message.ourItems[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string message = 4; */
        if (message.message !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.SendTradeOfferRequest
 */
export const SendTradeOfferRequest = new SendTradeOfferRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SendTradeOfferResponse$Type extends MessageType<SendTradeOfferResponse> {
    constructor() {
        super("steam.SendTradeOfferResponse", [
            { no: 1, name: "offer_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SendTradeOfferResponse>): SendTradeOfferResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.offerId = "";
        message.status = "";
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<SendTradeOfferResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SendTradeOfferResponse): SendTradeOfferResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string offer_id */ 1:
                    message.offerId = reader.string();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                case /* string error */ 3:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SendTradeOfferResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string offer_id = 1; */
        if (message.offerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.offerId);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        /* string error = 3; */
        if (message.error !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.SendTradeOfferResponse
 */
export const SendTradeOfferResponse = new SendTradeOfferResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTradeOfferStatusRequest$Type extends MessageType<GetTradeOfferStatusRequest> {
    constructor() {
        super("steam.GetTradeOfferStatusRequest", [
            { no: 1, name: "offer_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetTradeOfferStatusRequest>): GetTradeOfferStatusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.offerId = "";
        if (value !== undefined)
            reflectionMergePartial<GetTradeOfferStatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTradeOfferStatusRequest): GetTradeOfferStatusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string offer_id */ 1:
                    message.offerId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTradeOfferStatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string offer_id = 1; */
        if (message.offerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.offerId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.GetTradeOfferStatusRequest
 */
export const GetTradeOfferStatusRequest = new GetTradeOfferStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTradeOfferStatusResponse$Type extends MessageType<GetTradeOfferStatusResponse> {
    constructor() {
        super("steam.GetTradeOfferStatusResponse", [
            { no: 1, name: "offer_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "received_items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => InventoryAsset },
            { no: 4, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetTradeOfferStatusResponse>): GetTradeOfferStatusResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.offerId = "";
        message.status = "";
        message.receivedItems = [];
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<GetTradeOfferStatusResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTradeOfferStatusResponse): GetTradeOfferStatusResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string offer_id */ 1:
                    message.offerId = reader.string();
                    break;
                case /* string status */ 2:
                    message.status = reader.string();
                    break;
                case /* repeated steam.InventoryAsset received_items */ 3:
                    message.receivedItems.push(InventoryAsset.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string error */ 4:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTradeOfferStatusResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string offer_id = 1; */
        if (message.offerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.offerId);
        /* string status = 2; */
        if (message.status !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.status);
        /* repeated steam.InventoryAsset received_items = 3; */
        for (let i = 0; i < message.receivedItems.length; i++)
            InventoryAsset.internalBinaryWrite(message.receivedItems[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string error = 4; */
        if (message.error !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.GetTradeOfferStatusResponse
 */
export const GetTradeOfferStatusResponse = new GetTradeOfferStatusResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CancelTradeOfferRequest$Type extends MessageType<CancelTradeOfferRequest> {
    constructor() {
        super("steam.CancelTradeOfferRequest", [
            { no: 1, name: "offer_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CancelTradeOfferRequest>): CancelTradeOfferRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.offerId = "";
        if (value !== undefined)
            reflectionMergePartial<CancelTradeOfferRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CancelTradeOfferRequest): CancelTradeOfferRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string offer_id */ 1:
                    message.offerId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CancelTradeOfferRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string offer_id = 1; */
        if (message.offerId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.offerId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.CancelTradeOfferRequest
 */
export const CancelTradeOfferRequest = new CancelTradeOfferRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CancelTradeOfferResponse$Type extends MessageType<CancelTradeOfferResponse> {
    constructor() {
        super("steam.CancelTradeOfferResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CancelTradeOfferResponse>): CancelTradeOfferResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<CancelTradeOfferResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CancelTradeOfferResponse): CancelTradeOfferResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string error */ 2:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CancelTradeOfferResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string error = 2; */
        if (message.error !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.CancelTradeOfferResponse
 */
export const CancelTradeOfferResponse = new CancelTradeOfferResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCaseWhitelistRequest$Type extends MessageType<GetCaseWhitelistRequest> {
    constructor() {
        super("steam.GetCaseWhitelistRequest", []);
    }
    create(value?: PartialMessage<GetCaseWhitelistRequest>): GetCaseWhitelistRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetCaseWhitelistRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCaseWhitelistRequest): GetCaseWhitelistRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCaseWhitelistRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.GetCaseWhitelistRequest
 */
export const GetCaseWhitelistRequest = new GetCaseWhitelistRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetCaseWhitelistResponse$Type extends MessageType<GetCaseWhitelistResponse> {
    constructor() {
        super("steam.GetCaseWhitelistResponse", [
            { no: 1, name: "cases", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CaseInfo }
        ]);
    }
    create(value?: PartialMessage<GetCaseWhitelistResponse>): GetCaseWhitelistResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cases = [];
        if (value !== undefined)
            reflectionMergePartial<GetCaseWhitelistResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetCaseWhitelistResponse): GetCaseWhitelistResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated steam.CaseInfo cases */ 1:
                    message.cases.push(CaseInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetCaseWhitelistResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated steam.CaseInfo cases = 1; */
        for (let i = 0; i < message.cases.length; i++)
            CaseInfo.internalBinaryWrite(message.cases[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.GetCaseWhitelistResponse
 */
export const GetCaseWhitelistResponse = new GetCaseWhitelistResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValidateTradeUrlRequest$Type extends MessageType<ValidateTradeUrlRequest> {
    constructor() {
        super("steam.ValidateTradeUrlRequest", [
            { no: 1, name: "trade_url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "steam_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ValidateTradeUrlRequest>): ValidateTradeUrlRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tradeUrl = "";
        message.steamId = "";
        if (value !== undefined)
            reflectionMergePartial<ValidateTradeUrlRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValidateTradeUrlRequest): ValidateTradeUrlRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string trade_url */ 1:
                    message.tradeUrl = reader.string();
                    break;
                case /* string steam_id */ 2:
                    message.steamId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ValidateTradeUrlRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string trade_url = 1; */
        if (message.tradeUrl !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.tradeUrl);
        /* string steam_id = 2; */
        if (message.steamId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.steamId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.ValidateTradeUrlRequest
 */
export const ValidateTradeUrlRequest = new ValidateTradeUrlRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValidateTradeUrlResponse$Type extends MessageType<ValidateTradeUrlResponse> {
    constructor() {
        super("steam.ValidateTradeUrlResponse", [
            { no: 1, name: "valid", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "partner_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ValidateTradeUrlResponse>): ValidateTradeUrlResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.valid = false;
        message.partnerId = "";
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<ValidateTradeUrlResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValidateTradeUrlResponse): ValidateTradeUrlResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool valid */ 1:
                    message.valid = reader.bool();
                    break;
                case /* string partner_id */ 2:
                    message.partnerId = reader.string();
                    break;
                case /* string error */ 3:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ValidateTradeUrlResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool valid = 1; */
        if (message.valid !== false)
            writer.tag(1, WireType.Varint).bool(message.valid);
        /* string partner_id = 2; */
        if (message.partnerId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.partnerId);
        /* string error = 3; */
        if (message.error !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.ValidateTradeUrlResponse
 */
export const ValidateTradeUrlResponse = new ValidateTradeUrlResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBotInventoryRequest$Type extends MessageType<GetBotInventoryRequest> {
    constructor() {
        super("steam.GetBotInventoryRequest", [
            { no: 1, name: "cases_only", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<GetBotInventoryRequest>): GetBotInventoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.casesOnly = false;
        if (value !== undefined)
            reflectionMergePartial<GetBotInventoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetBotInventoryRequest): GetBotInventoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool cases_only */ 1:
                    message.casesOnly = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetBotInventoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool cases_only = 1; */
        if (message.casesOnly !== false)
            writer.tag(1, WireType.Varint).bool(message.casesOnly);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.GetBotInventoryRequest
 */
export const GetBotInventoryRequest = new GetBotInventoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetBotInventoryResponse$Type extends MessageType<GetBotInventoryResponse> {
    constructor() {
        super("steam.GetBotInventoryResponse", [
            { no: 1, name: "items", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => InventoryItem },
            { no: 2, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetBotInventoryResponse>): GetBotInventoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.items = [];
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<GetBotInventoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetBotInventoryResponse): GetBotInventoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated steam.InventoryItem items */ 1:
                    message.items.push(InventoryItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string error */ 2:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetBotInventoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated steam.InventoryItem items = 1; */
        for (let i = 0; i < message.items.length; i++)
            InventoryItem.internalBinaryWrite(message.items[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string error = 2; */
        if (message.error !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message steam.GetBotInventoryResponse
 */
export const GetBotInventoryResponse = new GetBotInventoryResponse$Type();
/**
 * @generated ServiceType for protobuf service steam.SteamService
 */
export const SteamService = new ServiceType("steam.SteamService", [
    { name: "GetProfile", options: {}, I: GetProfileRequest, O: GetProfileResponse },
    { name: "GetInventory", options: {}, I: GetInventoryRequest, O: GetInventoryResponse },
    { name: "GetBotInventory", options: {}, I: GetBotInventoryRequest, O: GetBotInventoryResponse },
    { name: "SendTradeOffer", options: {}, I: SendTradeOfferRequest, O: SendTradeOfferResponse },
    { name: "GetTradeOfferStatus", options: {}, I: GetTradeOfferStatusRequest, O: GetTradeOfferStatusResponse },
    { name: "CancelTradeOffer", options: {}, I: CancelTradeOfferRequest, O: CancelTradeOfferResponse },
    { name: "ValidateTradeUrl", options: {}, I: ValidateTradeUrlRequest, O: ValidateTradeUrlResponse },
    { name: "GetCaseWhitelist", options: {}, I: GetCaseWhitelistRequest, O: GetCaseWhitelistResponse }
]);
