// @generated by protobuf-ts 2.11.1 with parameter long_type_string,generate_dependencies,output_typescript,client_grpc1,server_grpc1
// @generated from protobuf file "steam/steam.proto" (package "steam", syntax proto3)
// tslint:disable
import { SteamService } from "./steam";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { GetCaseWhitelistResponse } from "./steam";
import type { GetCaseWhitelistRequest } from "./steam";
import type { ValidateTradeUrlResponse } from "./steam";
import type { ValidateTradeUrlRequest } from "./steam";
import type { CancelTradeOfferResponse } from "./steam";
import type { CancelTradeOfferRequest } from "./steam";
import type { GetTradeOfferStatusResponse } from "./steam";
import type { GetTradeOfferStatusRequest } from "./steam";
import type { SendTradeOfferResponse } from "./steam";
import type { SendTradeOfferRequest } from "./steam";
import type { GetBotInventoryResponse } from "./steam";
import type { GetBotInventoryRequest } from "./steam";
import type { GetInventoryResponse } from "./steam";
import type { GetInventoryRequest } from "./steam";
import type { GetProfileResponse } from "./steam";
import type { GetProfileRequest } from "./steam";
import * as grpc from "@grpc/grpc-js";
// ============================================================================
// Service
// ============================================================================

/**
 * @generated from protobuf service steam.SteamService
 */
export interface ISteamServiceClient {
    /**
     * Profile operations
     *
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetProfileResponse) => void): grpc.ClientUnaryCall;
    getProfile(input: GetProfileRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetProfileResponse) => void): grpc.ClientUnaryCall;
    getProfile(input: GetProfileRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetProfileResponse) => void): grpc.ClientUnaryCall;
    getProfile(input: GetProfileRequest, callback: (err: grpc.ServiceError | null, value?: GetProfileResponse) => void): grpc.ClientUnaryCall;
    /**
     * Inventory operations
     *
     * @generated from protobuf rpc: GetInventory
     */
    getInventory(input: GetInventoryRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetInventoryResponse) => void): grpc.ClientUnaryCall;
    getInventory(input: GetInventoryRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetInventoryResponse) => void): grpc.ClientUnaryCall;
    getInventory(input: GetInventoryRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetInventoryResponse) => void): grpc.ClientUnaryCall;
    getInventory(input: GetInventoryRequest, callback: (err: grpc.ServiceError | null, value?: GetInventoryResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: GetBotInventory
     */
    getBotInventory(input: GetBotInventoryRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetBotInventoryResponse) => void): grpc.ClientUnaryCall;
    getBotInventory(input: GetBotInventoryRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetBotInventoryResponse) => void): grpc.ClientUnaryCall;
    getBotInventory(input: GetBotInventoryRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetBotInventoryResponse) => void): grpc.ClientUnaryCall;
    getBotInventory(input: GetBotInventoryRequest, callback: (err: grpc.ServiceError | null, value?: GetBotInventoryResponse) => void): grpc.ClientUnaryCall;
    /**
     * Trade operations
     *
     * @generated from protobuf rpc: SendTradeOffer
     */
    sendTradeOffer(input: SendTradeOfferRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SendTradeOfferResponse) => void): grpc.ClientUnaryCall;
    sendTradeOffer(input: SendTradeOfferRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: SendTradeOfferResponse) => void): grpc.ClientUnaryCall;
    sendTradeOffer(input: SendTradeOfferRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: SendTradeOfferResponse) => void): grpc.ClientUnaryCall;
    sendTradeOffer(input: SendTradeOfferRequest, callback: (err: grpc.ServiceError | null, value?: SendTradeOfferResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: GetTradeOfferStatus
     */
    getTradeOfferStatus(input: GetTradeOfferStatusRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetTradeOfferStatusResponse) => void): grpc.ClientUnaryCall;
    getTradeOfferStatus(input: GetTradeOfferStatusRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetTradeOfferStatusResponse) => void): grpc.ClientUnaryCall;
    getTradeOfferStatus(input: GetTradeOfferStatusRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetTradeOfferStatusResponse) => void): grpc.ClientUnaryCall;
    getTradeOfferStatus(input: GetTradeOfferStatusRequest, callback: (err: grpc.ServiceError | null, value?: GetTradeOfferStatusResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: CancelTradeOffer
     */
    cancelTradeOffer(input: CancelTradeOfferRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: CancelTradeOfferResponse) => void): grpc.ClientUnaryCall;
    cancelTradeOffer(input: CancelTradeOfferRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: CancelTradeOfferResponse) => void): grpc.ClientUnaryCall;
    cancelTradeOffer(input: CancelTradeOfferRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: CancelTradeOfferResponse) => void): grpc.ClientUnaryCall;
    cancelTradeOffer(input: CancelTradeOfferRequest, callback: (err: grpc.ServiceError | null, value?: CancelTradeOfferResponse) => void): grpc.ClientUnaryCall;
    /**
     * Validation
     *
     * @generated from protobuf rpc: ValidateTradeUrl
     */
    validateTradeUrl(input: ValidateTradeUrlRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ValidateTradeUrlResponse) => void): grpc.ClientUnaryCall;
    validateTradeUrl(input: ValidateTradeUrlRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: ValidateTradeUrlResponse) => void): grpc.ClientUnaryCall;
    validateTradeUrl(input: ValidateTradeUrlRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: ValidateTradeUrlResponse) => void): grpc.ClientUnaryCall;
    validateTradeUrl(input: ValidateTradeUrlRequest, callback: (err: grpc.ServiceError | null, value?: ValidateTradeUrlResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: GetCaseWhitelist
     */
    getCaseWhitelist(input: GetCaseWhitelistRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetCaseWhitelistResponse) => void): grpc.ClientUnaryCall;
    getCaseWhitelist(input: GetCaseWhitelistRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetCaseWhitelistResponse) => void): grpc.ClientUnaryCall;
    getCaseWhitelist(input: GetCaseWhitelistRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetCaseWhitelistResponse) => void): grpc.ClientUnaryCall;
    getCaseWhitelist(input: GetCaseWhitelistRequest, callback: (err: grpc.ServiceError | null, value?: GetCaseWhitelistResponse) => void): grpc.ClientUnaryCall;
}
// ============================================================================
// Service
// ============================================================================

/**
 * @generated from protobuf service steam.SteamService
 */
export class SteamServiceClient extends grpc.Client implements ISteamServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * Profile operations
     *
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetProfileResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetProfileResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetProfileResponse) => void)): grpc.ClientUnaryCall {
        const method = SteamService.methods[0];
        return this.makeUnaryRequest<GetProfileRequest, GetProfileResponse>(`/${SteamService.typeName}/${method.name}`, (value: GetProfileRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetProfileResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Inventory operations
     *
     * @generated from protobuf rpc: GetInventory
     */
    getInventory(input: GetInventoryRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetInventoryResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetInventoryResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetInventoryResponse) => void)): grpc.ClientUnaryCall {
        const method = SteamService.methods[1];
        return this.makeUnaryRequest<GetInventoryRequest, GetInventoryResponse>(`/${SteamService.typeName}/${method.name}`, (value: GetInventoryRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetInventoryResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: GetBotInventory
     */
    getBotInventory(input: GetBotInventoryRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetBotInventoryResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetBotInventoryResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetBotInventoryResponse) => void)): grpc.ClientUnaryCall {
        const method = SteamService.methods[2];
        return this.makeUnaryRequest<GetBotInventoryRequest, GetBotInventoryResponse>(`/${SteamService.typeName}/${method.name}`, (value: GetBotInventoryRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetBotInventoryResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Trade operations
     *
     * @generated from protobuf rpc: SendTradeOffer
     */
    sendTradeOffer(input: SendTradeOfferRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SendTradeOfferResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: SendTradeOfferResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: SendTradeOfferResponse) => void)): grpc.ClientUnaryCall {
        const method = SteamService.methods[3];
        return this.makeUnaryRequest<SendTradeOfferRequest, SendTradeOfferResponse>(`/${SteamService.typeName}/${method.name}`, (value: SendTradeOfferRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): SendTradeOfferResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: GetTradeOfferStatus
     */
    getTradeOfferStatus(input: GetTradeOfferStatusRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetTradeOfferStatusResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetTradeOfferStatusResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetTradeOfferStatusResponse) => void)): grpc.ClientUnaryCall {
        const method = SteamService.methods[4];
        return this.makeUnaryRequest<GetTradeOfferStatusRequest, GetTradeOfferStatusResponse>(`/${SteamService.typeName}/${method.name}`, (value: GetTradeOfferStatusRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetTradeOfferStatusResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: CancelTradeOffer
     */
    cancelTradeOffer(input: CancelTradeOfferRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: CancelTradeOfferResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: CancelTradeOfferResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: CancelTradeOfferResponse) => void)): grpc.ClientUnaryCall {
        const method = SteamService.methods[5];
        return this.makeUnaryRequest<CancelTradeOfferRequest, CancelTradeOfferResponse>(`/${SteamService.typeName}/${method.name}`, (value: CancelTradeOfferRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): CancelTradeOfferResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Validation
     *
     * @generated from protobuf rpc: ValidateTradeUrl
     */
    validateTradeUrl(input: ValidateTradeUrlRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ValidateTradeUrlResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: ValidateTradeUrlResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: ValidateTradeUrlResponse) => void)): grpc.ClientUnaryCall {
        const method = SteamService.methods[6];
        return this.makeUnaryRequest<ValidateTradeUrlRequest, ValidateTradeUrlResponse>(`/${SteamService.typeName}/${method.name}`, (value: ValidateTradeUrlRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): ValidateTradeUrlResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: GetCaseWhitelist
     */
    getCaseWhitelist(input: GetCaseWhitelistRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetCaseWhitelistResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetCaseWhitelistResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetCaseWhitelistResponse) => void)): grpc.ClientUnaryCall {
        const method = SteamService.methods[7];
        return this.makeUnaryRequest<GetCaseWhitelistRequest, GetCaseWhitelistResponse>(`/${SteamService.typeName}/${method.name}`, (value: GetCaseWhitelistRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetCaseWhitelistResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
