// @generated by protobuf-ts 2.11.1 with parameter long_type_string,generate_dependencies,output_typescript,client_grpc1,server_grpc1
// @generated from protobuf file "polymarket/polymarket.proto" (package "polymarket", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
// ============================================================================
// Messages
// ============================================================================

/**
 * @generated from protobuf message polymarket.Market
 */
export interface Market {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string question = 2
     */
    question: string;
    /**
     * @generated from protobuf field: string slug = 3
     */
    slug: string;
    /**
     * @generated from protobuf field: string icon = 4
     */
    icon: string;
    /**
     * @generated from protobuf field: bool closed = 5
     */
    closed: boolean;
    /**
     * @generated from protobuf field: repeated string outcomes = 6
     */
    outcomes: string[]; // ["Yes", "No"]
    /**
     * @generated from protobuf field: repeated double outcome_prices = 7
     */
    outcomePrices: number[]; // [0.65, 0.35]
    /**
     * @generated from protobuf field: double volume = 8
     */
    volume: number;
    /**
     * @generated from protobuf field: double volume_24hr = 9
     */
    volume24Hr: number;
    /**
     * @generated from protobuf field: double liquidity = 10
     */
    liquidity: number;
    /**
     * @generated from protobuf field: string group_item_title = 11
     */
    groupItemTitle: string;
    /**
     * @generated from protobuf field: string resolution_status = 12
     */
    resolutionStatus: string; // From UMA: "", "proposed", "disputed", "resolved"
    /**
     * @generated from protobuf field: string end_date = 13
     */
    endDate: string; // ISO timestamp - when event ends
    /**
     * @generated from protobuf field: string winning_outcome = 14
     */
    winningOutcome: string; // Set when resolved: "Yes" or "No"
    /**
     * @generated from protobuf field: string uma_end_date = 15
     */
    umaEndDate: string; // ISO timestamp - when oracle resolution is final
}
/**
 * @generated from protobuf message polymarket.MarketResolution
 */
export interface MarketResolution {
    /**
     * @generated from protobuf field: string slug = 1
     */
    slug: string;
    /**
     * @generated from protobuf field: string market_id = 2
     */
    marketId: string;
    /**
     * @generated from protobuf field: string winning_outcome = 3
     */
    winningOutcome: string; // "Yes" or "No"
    /**
     * @generated from protobuf field: string resolved_at = 4
     */
    resolvedAt: string; // ISO timestamp
    /**
     * @generated from protobuf field: bool is_disputed = 5
     */
    isDisputed: boolean;
    /**
     * @generated from protobuf field: bool dispute_resolved = 6
     */
    disputeResolved: boolean;
}
// ============================================================================
// Requests / Responses
// ============================================================================

/**
 * GetMarkets - get all tracked markets
 *
 * @generated from protobuf message polymarket.GetMarketsRequest
 */
export interface GetMarketsRequest {
    /**
     * @generated from protobuf field: repeated string slugs = 1
     */
    slugs: string[]; // If empty, get all tracked
}
/**
 * @generated from protobuf message polymarket.GetMarketsResponse
 */
export interface GetMarketsResponse {
    /**
     * @generated from protobuf field: repeated polymarket.Market markets = 1
     */
    markets: Market[];
    /**
     * @generated from protobuf field: bool from_cache = 2
     */
    fromCache: boolean;
}
/**
 * GetMarket - get a specific market
 *
 * @generated from protobuf message polymarket.GetMarketRequest
 */
export interface GetMarketRequest {
    /**
     * @generated from protobuf field: string slug = 1
     */
    slug: string;
    /**
     * @generated from protobuf field: string market_id = 2
     */
    marketId: string; // For multi-outcome events
}
/**
 * @generated from protobuf message polymarket.GetMarketResponse
 */
export interface GetMarketResponse {
    /**
     * @generated from protobuf field: polymarket.Market market = 1
     */
    market?: Market;
    /**
     * @generated from protobuf field: bool from_cache = 2
     */
    fromCache: boolean;
    /**
     * @generated from protobuf field: string error = 3
     */
    error: string; // "not_found"
}
/**
 * FetchMarket - fetch market data from Polymarket API (not cache)
 *
 * @generated from protobuf message polymarket.FetchMarketRequest
 */
export interface FetchMarketRequest {
    /**
     * @generated from protobuf field: string slug = 1
     */
    slug: string;
}
/**
 * @generated from protobuf message polymarket.FetchMarketResponse
 */
export interface FetchMarketResponse {
    /**
     * @generated from protobuf field: repeated polymarket.Market markets = 1
     */
    markets: Market[]; // Multiple markets for multi-outcome events
    /**
     * @generated from protobuf field: string error = 2
     */
    error: string; // "not_found", "api_error"
}
/**
 * CheckResolutions - check for newly resolved markets
 *
 * @generated from protobuf message polymarket.CheckResolutionsRequest
 */
export interface CheckResolutionsRequest {
    /**
     * @generated from protobuf field: repeated string slugs = 1
     */
    slugs: string[]; // If empty, check all tracked
}
/**
 * @generated from protobuf message polymarket.CheckResolutionsResponse
 */
export interface CheckResolutionsResponse {
    /**
     * @generated from protobuf field: repeated polymarket.MarketResolution resolutions = 1
     */
    resolutions: MarketResolution[];
}
/**
 * AddTrackedMarket - add a market to track
 *
 * @generated from protobuf message polymarket.AddTrackedMarketRequest
 */
export interface AddTrackedMarketRequest {
    /**
     * @generated from protobuf field: string slug = 1
     */
    slug: string;
    /**
     * @generated from protobuf field: string market_id = 2
     */
    marketId: string; // Optional: for specific market in event
}
/**
 * @generated from protobuf message polymarket.AddTrackedMarketResponse
 */
export interface AddTrackedMarketResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: polymarket.Market market = 2
     */
    market?: Market;
    /**
     * @generated from protobuf field: string error = 3
     */
    error: string; // "already_tracked", "not_found"
}
/**
 * RemoveTrackedMarket
 *
 * @generated from protobuf message polymarket.RemoveTrackedMarketRequest
 */
export interface RemoveTrackedMarketRequest {
    /**
     * @generated from protobuf field: string slug = 1
     */
    slug: string;
    /**
     * @generated from protobuf field: string market_id = 2
     */
    marketId: string;
}
/**
 * @generated from protobuf message polymarket.RemoveTrackedMarketResponse
 */
export interface RemoveTrackedMarketResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
    /**
     * @generated from protobuf field: string error = 2
     */
    error: string;
}
/**
 * GetTrackedMarkets
 *
 * @generated from protobuf message polymarket.GetTrackedMarketsRequest
 */
export interface GetTrackedMarketsRequest {
}
/**
 * @generated from protobuf message polymarket.GetTrackedMarketsResponse
 */
export interface GetTrackedMarketsResponse {
    /**
     * @generated from protobuf field: repeated string slugs = 1
     */
    slugs: string[];
    /**
     * @generated from protobuf field: repeated string slug_ids = 2
     */
    slugIds: string[]; // "slug:marketId" pairs
}
// @generated message type with reflection information, may provide speed optimized methods
class Market$Type extends MessageType<Market> {
    constructor() {
        super("polymarket.Market", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "question", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "icon", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "closed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "outcomes", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "outcome_prices", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "volume", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "volume_24hr", kind: "scalar", jsonName: "volume24hr", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 10, name: "liquidity", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 11, name: "group_item_title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "resolution_status", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 13, name: "end_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 14, name: "winning_outcome", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "uma_end_date", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Market>): Market {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.question = "";
        message.slug = "";
        message.icon = "";
        message.closed = false;
        message.outcomes = [];
        message.outcomePrices = [];
        message.volume = 0;
        message.volume24Hr = 0;
        message.liquidity = 0;
        message.groupItemTitle = "";
        message.resolutionStatus = "";
        message.endDate = "";
        message.winningOutcome = "";
        message.umaEndDate = "";
        if (value !== undefined)
            reflectionMergePartial<Market>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Market): Market {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string question */ 2:
                    message.question = reader.string();
                    break;
                case /* string slug */ 3:
                    message.slug = reader.string();
                    break;
                case /* string icon */ 4:
                    message.icon = reader.string();
                    break;
                case /* bool closed */ 5:
                    message.closed = reader.bool();
                    break;
                case /* repeated string outcomes */ 6:
                    message.outcomes.push(reader.string());
                    break;
                case /* repeated double outcome_prices */ 7:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.outcomePrices.push(reader.double());
                    else
                        message.outcomePrices.push(reader.double());
                    break;
                case /* double volume */ 8:
                    message.volume = reader.double();
                    break;
                case /* double volume_24hr */ 9:
                    message.volume24Hr = reader.double();
                    break;
                case /* double liquidity */ 10:
                    message.liquidity = reader.double();
                    break;
                case /* string group_item_title */ 11:
                    message.groupItemTitle = reader.string();
                    break;
                case /* string resolution_status */ 12:
                    message.resolutionStatus = reader.string();
                    break;
                case /* string end_date */ 13:
                    message.endDate = reader.string();
                    break;
                case /* string winning_outcome */ 14:
                    message.winningOutcome = reader.string();
                    break;
                case /* string uma_end_date */ 15:
                    message.umaEndDate = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Market, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string question = 2; */
        if (message.question !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.question);
        /* string slug = 3; */
        if (message.slug !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.slug);
        /* string icon = 4; */
        if (message.icon !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.icon);
        /* bool closed = 5; */
        if (message.closed !== false)
            writer.tag(5, WireType.Varint).bool(message.closed);
        /* repeated string outcomes = 6; */
        for (let i = 0; i < message.outcomes.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.outcomes[i]);
        /* repeated double outcome_prices = 7; */
        if (message.outcomePrices.length) {
            writer.tag(7, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.outcomePrices.length; i++)
                writer.double(message.outcomePrices[i]);
            writer.join();
        }
        /* double volume = 8; */
        if (message.volume !== 0)
            writer.tag(8, WireType.Bit64).double(message.volume);
        /* double volume_24hr = 9; */
        if (message.volume24Hr !== 0)
            writer.tag(9, WireType.Bit64).double(message.volume24Hr);
        /* double liquidity = 10; */
        if (message.liquidity !== 0)
            writer.tag(10, WireType.Bit64).double(message.liquidity);
        /* string group_item_title = 11; */
        if (message.groupItemTitle !== "")
            writer.tag(11, WireType.LengthDelimited).string(message.groupItemTitle);
        /* string resolution_status = 12; */
        if (message.resolutionStatus !== "")
            writer.tag(12, WireType.LengthDelimited).string(message.resolutionStatus);
        /* string end_date = 13; */
        if (message.endDate !== "")
            writer.tag(13, WireType.LengthDelimited).string(message.endDate);
        /* string winning_outcome = 14; */
        if (message.winningOutcome !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.winningOutcome);
        /* string uma_end_date = 15; */
        if (message.umaEndDate !== "")
            writer.tag(15, WireType.LengthDelimited).string(message.umaEndDate);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.Market
 */
export const Market = new Market$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MarketResolution$Type extends MessageType<MarketResolution> {
    constructor() {
        super("polymarket.MarketResolution", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "market_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "winning_outcome", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "resolved_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "is_disputed", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "dispute_resolved", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<MarketResolution>): MarketResolution {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        message.marketId = "";
        message.winningOutcome = "";
        message.resolvedAt = "";
        message.isDisputed = false;
        message.disputeResolved = false;
        if (value !== undefined)
            reflectionMergePartial<MarketResolution>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MarketResolution): MarketResolution {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                case /* string market_id */ 2:
                    message.marketId = reader.string();
                    break;
                case /* string winning_outcome */ 3:
                    message.winningOutcome = reader.string();
                    break;
                case /* string resolved_at */ 4:
                    message.resolvedAt = reader.string();
                    break;
                case /* bool is_disputed */ 5:
                    message.isDisputed = reader.bool();
                    break;
                case /* bool dispute_resolved */ 6:
                    message.disputeResolved = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MarketResolution, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        /* string market_id = 2; */
        if (message.marketId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.marketId);
        /* string winning_outcome = 3; */
        if (message.winningOutcome !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.winningOutcome);
        /* string resolved_at = 4; */
        if (message.resolvedAt !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.resolvedAt);
        /* bool is_disputed = 5; */
        if (message.isDisputed !== false)
            writer.tag(5, WireType.Varint).bool(message.isDisputed);
        /* bool dispute_resolved = 6; */
        if (message.disputeResolved !== false)
            writer.tag(6, WireType.Varint).bool(message.disputeResolved);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.MarketResolution
 */
export const MarketResolution = new MarketResolution$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMarketsRequest$Type extends MessageType<GetMarketsRequest> {
    constructor() {
        super("polymarket.GetMarketsRequest", [
            { no: 1, name: "slugs", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetMarketsRequest>): GetMarketsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slugs = [];
        if (value !== undefined)
            reflectionMergePartial<GetMarketsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMarketsRequest): GetMarketsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string slugs */ 1:
                    message.slugs.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMarketsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string slugs = 1; */
        for (let i = 0; i < message.slugs.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.slugs[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.GetMarketsRequest
 */
export const GetMarketsRequest = new GetMarketsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMarketsResponse$Type extends MessageType<GetMarketsResponse> {
    constructor() {
        super("polymarket.GetMarketsResponse", [
            { no: 1, name: "markets", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Market },
            { no: 2, name: "from_cache", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<GetMarketsResponse>): GetMarketsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.markets = [];
        message.fromCache = false;
        if (value !== undefined)
            reflectionMergePartial<GetMarketsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMarketsResponse): GetMarketsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polymarket.Market markets */ 1:
                    message.markets.push(Market.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bool from_cache */ 2:
                    message.fromCache = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMarketsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polymarket.Market markets = 1; */
        for (let i = 0; i < message.markets.length; i++)
            Market.internalBinaryWrite(message.markets[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool from_cache = 2; */
        if (message.fromCache !== false)
            writer.tag(2, WireType.Varint).bool(message.fromCache);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.GetMarketsResponse
 */
export const GetMarketsResponse = new GetMarketsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMarketRequest$Type extends MessageType<GetMarketRequest> {
    constructor() {
        super("polymarket.GetMarketRequest", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "market_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetMarketRequest>): GetMarketRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        message.marketId = "";
        if (value !== undefined)
            reflectionMergePartial<GetMarketRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMarketRequest): GetMarketRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                case /* string market_id */ 2:
                    message.marketId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMarketRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        /* string market_id = 2; */
        if (message.marketId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.marketId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.GetMarketRequest
 */
export const GetMarketRequest = new GetMarketRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMarketResponse$Type extends MessageType<GetMarketResponse> {
    constructor() {
        super("polymarket.GetMarketResponse", [
            { no: 1, name: "market", kind: "message", T: () => Market },
            { no: 2, name: "from_cache", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetMarketResponse>): GetMarketResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fromCache = false;
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<GetMarketResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMarketResponse): GetMarketResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* polymarket.Market market */ 1:
                    message.market = Market.internalBinaryRead(reader, reader.uint32(), options, message.market);
                    break;
                case /* bool from_cache */ 2:
                    message.fromCache = reader.bool();
                    break;
                case /* string error */ 3:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMarketResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* polymarket.Market market = 1; */
        if (message.market)
            Market.internalBinaryWrite(message.market, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool from_cache = 2; */
        if (message.fromCache !== false)
            writer.tag(2, WireType.Varint).bool(message.fromCache);
        /* string error = 3; */
        if (message.error !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.GetMarketResponse
 */
export const GetMarketResponse = new GetMarketResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FetchMarketRequest$Type extends MessageType<FetchMarketRequest> {
    constructor() {
        super("polymarket.FetchMarketRequest", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<FetchMarketRequest>): FetchMarketRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        if (value !== undefined)
            reflectionMergePartial<FetchMarketRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FetchMarketRequest): FetchMarketRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FetchMarketRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.FetchMarketRequest
 */
export const FetchMarketRequest = new FetchMarketRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FetchMarketResponse$Type extends MessageType<FetchMarketResponse> {
    constructor() {
        super("polymarket.FetchMarketResponse", [
            { no: 1, name: "markets", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Market },
            { no: 2, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<FetchMarketResponse>): FetchMarketResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.markets = [];
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<FetchMarketResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: FetchMarketResponse): FetchMarketResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polymarket.Market markets */ 1:
                    message.markets.push(Market.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string error */ 2:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: FetchMarketResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polymarket.Market markets = 1; */
        for (let i = 0; i < message.markets.length; i++)
            Market.internalBinaryWrite(message.markets[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* string error = 2; */
        if (message.error !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.FetchMarketResponse
 */
export const FetchMarketResponse = new FetchMarketResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CheckResolutionsRequest$Type extends MessageType<CheckResolutionsRequest> {
    constructor() {
        super("polymarket.CheckResolutionsRequest", [
            { no: 1, name: "slugs", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CheckResolutionsRequest>): CheckResolutionsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slugs = [];
        if (value !== undefined)
            reflectionMergePartial<CheckResolutionsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CheckResolutionsRequest): CheckResolutionsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string slugs */ 1:
                    message.slugs.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CheckResolutionsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string slugs = 1; */
        for (let i = 0; i < message.slugs.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.slugs[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.CheckResolutionsRequest
 */
export const CheckResolutionsRequest = new CheckResolutionsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CheckResolutionsResponse$Type extends MessageType<CheckResolutionsResponse> {
    constructor() {
        super("polymarket.CheckResolutionsResponse", [
            { no: 1, name: "resolutions", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MarketResolution }
        ]);
    }
    create(value?: PartialMessage<CheckResolutionsResponse>): CheckResolutionsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.resolutions = [];
        if (value !== undefined)
            reflectionMergePartial<CheckResolutionsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CheckResolutionsResponse): CheckResolutionsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated polymarket.MarketResolution resolutions */ 1:
                    message.resolutions.push(MarketResolution.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CheckResolutionsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated polymarket.MarketResolution resolutions = 1; */
        for (let i = 0; i < message.resolutions.length; i++)
            MarketResolution.internalBinaryWrite(message.resolutions[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.CheckResolutionsResponse
 */
export const CheckResolutionsResponse = new CheckResolutionsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddTrackedMarketRequest$Type extends MessageType<AddTrackedMarketRequest> {
    constructor() {
        super("polymarket.AddTrackedMarketRequest", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "market_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AddTrackedMarketRequest>): AddTrackedMarketRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        message.marketId = "";
        if (value !== undefined)
            reflectionMergePartial<AddTrackedMarketRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddTrackedMarketRequest): AddTrackedMarketRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                case /* string market_id */ 2:
                    message.marketId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddTrackedMarketRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        /* string market_id = 2; */
        if (message.marketId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.marketId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.AddTrackedMarketRequest
 */
export const AddTrackedMarketRequest = new AddTrackedMarketRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AddTrackedMarketResponse$Type extends MessageType<AddTrackedMarketResponse> {
    constructor() {
        super("polymarket.AddTrackedMarketResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "market", kind: "message", T: () => Market },
            { no: 3, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AddTrackedMarketResponse>): AddTrackedMarketResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<AddTrackedMarketResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AddTrackedMarketResponse): AddTrackedMarketResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* polymarket.Market market */ 2:
                    message.market = Market.internalBinaryRead(reader, reader.uint32(), options, message.market);
                    break;
                case /* string error */ 3:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AddTrackedMarketResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* polymarket.Market market = 2; */
        if (message.market)
            Market.internalBinaryWrite(message.market, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string error = 3; */
        if (message.error !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.AddTrackedMarketResponse
 */
export const AddTrackedMarketResponse = new AddTrackedMarketResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoveTrackedMarketRequest$Type extends MessageType<RemoveTrackedMarketRequest> {
    constructor() {
        super("polymarket.RemoveTrackedMarketRequest", [
            { no: 1, name: "slug", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "market_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RemoveTrackedMarketRequest>): RemoveTrackedMarketRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slug = "";
        message.marketId = "";
        if (value !== undefined)
            reflectionMergePartial<RemoveTrackedMarketRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoveTrackedMarketRequest): RemoveTrackedMarketRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string slug */ 1:
                    message.slug = reader.string();
                    break;
                case /* string market_id */ 2:
                    message.marketId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoveTrackedMarketRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string slug = 1; */
        if (message.slug !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.slug);
        /* string market_id = 2; */
        if (message.marketId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.marketId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.RemoveTrackedMarketRequest
 */
export const RemoveTrackedMarketRequest = new RemoveTrackedMarketRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoveTrackedMarketResponse$Type extends MessageType<RemoveTrackedMarketResponse> {
    constructor() {
        super("polymarket.RemoveTrackedMarketResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "error", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RemoveTrackedMarketResponse>): RemoveTrackedMarketResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.error = "";
        if (value !== undefined)
            reflectionMergePartial<RemoveTrackedMarketResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoveTrackedMarketResponse): RemoveTrackedMarketResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                case /* string error */ 2:
                    message.error = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoveTrackedMarketResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        /* string error = 2; */
        if (message.error !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.error);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.RemoveTrackedMarketResponse
 */
export const RemoveTrackedMarketResponse = new RemoveTrackedMarketResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTrackedMarketsRequest$Type extends MessageType<GetTrackedMarketsRequest> {
    constructor() {
        super("polymarket.GetTrackedMarketsRequest", []);
    }
    create(value?: PartialMessage<GetTrackedMarketsRequest>): GetTrackedMarketsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetTrackedMarketsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTrackedMarketsRequest): GetTrackedMarketsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTrackedMarketsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.GetTrackedMarketsRequest
 */
export const GetTrackedMarketsRequest = new GetTrackedMarketsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTrackedMarketsResponse$Type extends MessageType<GetTrackedMarketsResponse> {
    constructor() {
        super("polymarket.GetTrackedMarketsResponse", [
            { no: 1, name: "slugs", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "slug_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetTrackedMarketsResponse>): GetTrackedMarketsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.slugs = [];
        message.slugIds = [];
        if (value !== undefined)
            reflectionMergePartial<GetTrackedMarketsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTrackedMarketsResponse): GetTrackedMarketsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated string slugs */ 1:
                    message.slugs.push(reader.string());
                    break;
                case /* repeated string slug_ids */ 2:
                    message.slugIds.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTrackedMarketsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated string slugs = 1; */
        for (let i = 0; i < message.slugs.length; i++)
            writer.tag(1, WireType.LengthDelimited).string(message.slugs[i]);
        /* repeated string slug_ids = 2; */
        for (let i = 0; i < message.slugIds.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.slugIds[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message polymarket.GetTrackedMarketsResponse
 */
export const GetTrackedMarketsResponse = new GetTrackedMarketsResponse$Type();
/**
 * @generated ServiceType for protobuf service polymarket.PolymarketService
 */
export const PolymarketService = new ServiceType("polymarket.PolymarketService", [
    { name: "GetMarkets", options: {}, I: GetMarketsRequest, O: GetMarketsResponse },
    { name: "GetMarket", options: {}, I: GetMarketRequest, O: GetMarketResponse },
    { name: "FetchMarket", options: {}, I: FetchMarketRequest, O: FetchMarketResponse },
    { name: "CheckResolutions", options: {}, I: CheckResolutionsRequest, O: CheckResolutionsResponse },
    { name: "AddTrackedMarket", options: {}, I: AddTrackedMarketRequest, O: AddTrackedMarketResponse },
    { name: "RemoveTrackedMarket", options: {}, I: RemoveTrackedMarketRequest, O: RemoveTrackedMarketResponse },
    { name: "GetTrackedMarkets", options: {}, I: GetTrackedMarketsRequest, O: GetTrackedMarketsResponse }
]);
