// @generated by protobuf-ts 2.11.1 with parameter long_type_string,generate_dependencies,output_typescript,client_grpc1,server_grpc1
// @generated from protobuf file "polymarket/polymarket.proto" (package "polymarket", syntax proto3)
// tslint:disable
import { GetTrackedMarketsResponse } from "./polymarket";
import { GetTrackedMarketsRequest } from "./polymarket";
import { RemoveTrackedMarketResponse } from "./polymarket";
import { RemoveTrackedMarketRequest } from "./polymarket";
import { AddTrackedMarketResponse } from "./polymarket";
import { AddTrackedMarketRequest } from "./polymarket";
import { CheckResolutionsResponse } from "./polymarket";
import { CheckResolutionsRequest } from "./polymarket";
import { FetchMarketResponse } from "./polymarket";
import { FetchMarketRequest } from "./polymarket";
import { GetMarketResponse } from "./polymarket";
import { GetMarketRequest } from "./polymarket";
import { GetMarketsResponse } from "./polymarket";
import { GetMarketsRequest } from "./polymarket";
import type * as grpc from "@grpc/grpc-js";
// ============================================================================
// Service
// ============================================================================

/**
 * @generated from protobuf service polymarket.PolymarketService
 */
export interface IPolymarketService extends grpc.UntypedServiceImplementation {
    /**
     * Market data
     *
     * @generated from protobuf rpc: GetMarkets
     */
    getMarkets: grpc.handleUnaryCall<GetMarketsRequest, GetMarketsResponse>;
    /**
     * @generated from protobuf rpc: GetMarket
     */
    getMarket: grpc.handleUnaryCall<GetMarketRequest, GetMarketResponse>;
    /**
     * @generated from protobuf rpc: FetchMarket
     */
    fetchMarket: grpc.handleUnaryCall<FetchMarketRequest, FetchMarketResponse>;
    /**
     * Resolution checking
     *
     * @generated from protobuf rpc: CheckResolutions
     */
    checkResolutions: grpc.handleUnaryCall<CheckResolutionsRequest, CheckResolutionsResponse>;
    /**
     * Market tracking management
     *
     * @generated from protobuf rpc: AddTrackedMarket
     */
    addTrackedMarket: grpc.handleUnaryCall<AddTrackedMarketRequest, AddTrackedMarketResponse>;
    /**
     * @generated from protobuf rpc: RemoveTrackedMarket
     */
    removeTrackedMarket: grpc.handleUnaryCall<RemoveTrackedMarketRequest, RemoveTrackedMarketResponse>;
    /**
     * @generated from protobuf rpc: GetTrackedMarkets
     */
    getTrackedMarkets: grpc.handleUnaryCall<GetTrackedMarketsRequest, GetTrackedMarketsResponse>;
}
/**
 * @grpc/grpc-js definition for the protobuf service polymarket.PolymarketService.
 *
 * Usage: Implement the interface IPolymarketService and add to a grpc server.
 *
 * ```typescript
 * const server = new grpc.Server();
 * const service: IPolymarketService = ...
 * server.addService(polymarketServiceDefinition, service);
 * ```
 */
export const polymarketServiceDefinition: grpc.ServiceDefinition<IPolymarketService> = {
    getMarkets: {
        path: "/polymarket.PolymarketService/GetMarkets",
        originalName: "GetMarkets",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetMarketsResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetMarketsRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetMarketsResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetMarketsRequest.toBinary(value))
    },
    getMarket: {
        path: "/polymarket.PolymarketService/GetMarket",
        originalName: "GetMarket",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetMarketResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetMarketRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetMarketResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetMarketRequest.toBinary(value))
    },
    fetchMarket: {
        path: "/polymarket.PolymarketService/FetchMarket",
        originalName: "FetchMarket",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => FetchMarketResponse.fromBinary(bytes),
        requestDeserialize: bytes => FetchMarketRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(FetchMarketResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(FetchMarketRequest.toBinary(value))
    },
    checkResolutions: {
        path: "/polymarket.PolymarketService/CheckResolutions",
        originalName: "CheckResolutions",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => CheckResolutionsResponse.fromBinary(bytes),
        requestDeserialize: bytes => CheckResolutionsRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(CheckResolutionsResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(CheckResolutionsRequest.toBinary(value))
    },
    addTrackedMarket: {
        path: "/polymarket.PolymarketService/AddTrackedMarket",
        originalName: "AddTrackedMarket",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => AddTrackedMarketResponse.fromBinary(bytes),
        requestDeserialize: bytes => AddTrackedMarketRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(AddTrackedMarketResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(AddTrackedMarketRequest.toBinary(value))
    },
    removeTrackedMarket: {
        path: "/polymarket.PolymarketService/RemoveTrackedMarket",
        originalName: "RemoveTrackedMarket",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => RemoveTrackedMarketResponse.fromBinary(bytes),
        requestDeserialize: bytes => RemoveTrackedMarketRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(RemoveTrackedMarketResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(RemoveTrackedMarketRequest.toBinary(value))
    },
    getTrackedMarkets: {
        path: "/polymarket.PolymarketService/GetTrackedMarkets",
        originalName: "GetTrackedMarkets",
        requestStream: false,
        responseStream: false,
        responseDeserialize: bytes => GetTrackedMarketsResponse.fromBinary(bytes),
        requestDeserialize: bytes => GetTrackedMarketsRequest.fromBinary(bytes),
        responseSerialize: value => Buffer.from(GetTrackedMarketsResponse.toBinary(value)),
        requestSerialize: value => Buffer.from(GetTrackedMarketsRequest.toBinary(value))
    }
};
