// @generated by protobuf-ts 2.11.1 with parameter long_type_string,generate_dependencies,output_typescript,client_grpc1,server_grpc1
// @generated from protobuf file "polymarket/polymarket.proto" (package "polymarket", syntax proto3)
// tslint:disable
import { PolymarketService } from "./polymarket";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { GetTrackedMarketsResponse } from "./polymarket";
import type { GetTrackedMarketsRequest } from "./polymarket";
import type { RemoveTrackedMarketResponse } from "./polymarket";
import type { RemoveTrackedMarketRequest } from "./polymarket";
import type { AddTrackedMarketResponse } from "./polymarket";
import type { AddTrackedMarketRequest } from "./polymarket";
import type { CheckResolutionsResponse } from "./polymarket";
import type { CheckResolutionsRequest } from "./polymarket";
import type { FetchMarketResponse } from "./polymarket";
import type { FetchMarketRequest } from "./polymarket";
import type { GetMarketResponse } from "./polymarket";
import type { GetMarketRequest } from "./polymarket";
import type { GetMarketsResponse } from "./polymarket";
import type { GetMarketsRequest } from "./polymarket";
import * as grpc from "@grpc/grpc-js";
// ============================================================================
// Service
// ============================================================================

/**
 * @generated from protobuf service polymarket.PolymarketService
 */
export interface IPolymarketServiceClient {
    /**
     * Market data
     *
     * @generated from protobuf rpc: GetMarkets
     */
    getMarkets(input: GetMarketsRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetMarketsResponse) => void): grpc.ClientUnaryCall;
    getMarkets(input: GetMarketsRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetMarketsResponse) => void): grpc.ClientUnaryCall;
    getMarkets(input: GetMarketsRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetMarketsResponse) => void): grpc.ClientUnaryCall;
    getMarkets(input: GetMarketsRequest, callback: (err: grpc.ServiceError | null, value?: GetMarketsResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: GetMarket
     */
    getMarket(input: GetMarketRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetMarketResponse) => void): grpc.ClientUnaryCall;
    getMarket(input: GetMarketRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetMarketResponse) => void): grpc.ClientUnaryCall;
    getMarket(input: GetMarketRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetMarketResponse) => void): grpc.ClientUnaryCall;
    getMarket(input: GetMarketRequest, callback: (err: grpc.ServiceError | null, value?: GetMarketResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: FetchMarket
     */
    fetchMarket(input: FetchMarketRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: FetchMarketResponse) => void): grpc.ClientUnaryCall;
    fetchMarket(input: FetchMarketRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: FetchMarketResponse) => void): grpc.ClientUnaryCall;
    fetchMarket(input: FetchMarketRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: FetchMarketResponse) => void): grpc.ClientUnaryCall;
    fetchMarket(input: FetchMarketRequest, callback: (err: grpc.ServiceError | null, value?: FetchMarketResponse) => void): grpc.ClientUnaryCall;
    /**
     * Resolution checking
     *
     * @generated from protobuf rpc: CheckResolutions
     */
    checkResolutions(input: CheckResolutionsRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: CheckResolutionsResponse) => void): grpc.ClientUnaryCall;
    checkResolutions(input: CheckResolutionsRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: CheckResolutionsResponse) => void): grpc.ClientUnaryCall;
    checkResolutions(input: CheckResolutionsRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: CheckResolutionsResponse) => void): grpc.ClientUnaryCall;
    checkResolutions(input: CheckResolutionsRequest, callback: (err: grpc.ServiceError | null, value?: CheckResolutionsResponse) => void): grpc.ClientUnaryCall;
    /**
     * Market tracking management
     *
     * @generated from protobuf rpc: AddTrackedMarket
     */
    addTrackedMarket(input: AddTrackedMarketRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: AddTrackedMarketResponse) => void): grpc.ClientUnaryCall;
    addTrackedMarket(input: AddTrackedMarketRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: AddTrackedMarketResponse) => void): grpc.ClientUnaryCall;
    addTrackedMarket(input: AddTrackedMarketRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: AddTrackedMarketResponse) => void): grpc.ClientUnaryCall;
    addTrackedMarket(input: AddTrackedMarketRequest, callback: (err: grpc.ServiceError | null, value?: AddTrackedMarketResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: RemoveTrackedMarket
     */
    removeTrackedMarket(input: RemoveTrackedMarketRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: RemoveTrackedMarketResponse) => void): grpc.ClientUnaryCall;
    removeTrackedMarket(input: RemoveTrackedMarketRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: RemoveTrackedMarketResponse) => void): grpc.ClientUnaryCall;
    removeTrackedMarket(input: RemoveTrackedMarketRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: RemoveTrackedMarketResponse) => void): grpc.ClientUnaryCall;
    removeTrackedMarket(input: RemoveTrackedMarketRequest, callback: (err: grpc.ServiceError | null, value?: RemoveTrackedMarketResponse) => void): grpc.ClientUnaryCall;
    /**
     * @generated from protobuf rpc: GetTrackedMarkets
     */
    getTrackedMarkets(input: GetTrackedMarketsRequest, metadata: grpc.Metadata, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetTrackedMarketsResponse) => void): grpc.ClientUnaryCall;
    getTrackedMarkets(input: GetTrackedMarketsRequest, metadata: grpc.Metadata, callback: (err: grpc.ServiceError | null, value?: GetTrackedMarketsResponse) => void): grpc.ClientUnaryCall;
    getTrackedMarkets(input: GetTrackedMarketsRequest, options: grpc.CallOptions, callback: (err: grpc.ServiceError | null, value?: GetTrackedMarketsResponse) => void): grpc.ClientUnaryCall;
    getTrackedMarkets(input: GetTrackedMarketsRequest, callback: (err: grpc.ServiceError | null, value?: GetTrackedMarketsResponse) => void): grpc.ClientUnaryCall;
}
// ============================================================================
// Service
// ============================================================================

/**
 * @generated from protobuf service polymarket.PolymarketService
 */
export class PolymarketServiceClient extends grpc.Client implements IPolymarketServiceClient {
    private readonly _binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions>;
    constructor(address: string, credentials: grpc.ChannelCredentials, options: grpc.ClientOptions = {}, binaryOptions: Partial<BinaryReadOptions & BinaryWriteOptions> = {}) {
        super(address, credentials, options);
        this._binaryOptions = binaryOptions;
    }
    /**
     * Market data
     *
     * @generated from protobuf rpc: GetMarkets
     */
    getMarkets(input: GetMarketsRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetMarketsResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetMarketsResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetMarketsResponse) => void)): grpc.ClientUnaryCall {
        const method = PolymarketService.methods[0];
        return this.makeUnaryRequest<GetMarketsRequest, GetMarketsResponse>(`/${PolymarketService.typeName}/${method.name}`, (value: GetMarketsRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetMarketsResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: GetMarket
     */
    getMarket(input: GetMarketRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetMarketResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetMarketResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetMarketResponse) => void)): grpc.ClientUnaryCall {
        const method = PolymarketService.methods[1];
        return this.makeUnaryRequest<GetMarketRequest, GetMarketResponse>(`/${PolymarketService.typeName}/${method.name}`, (value: GetMarketRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetMarketResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: FetchMarket
     */
    fetchMarket(input: FetchMarketRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: FetchMarketResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: FetchMarketResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: FetchMarketResponse) => void)): grpc.ClientUnaryCall {
        const method = PolymarketService.methods[2];
        return this.makeUnaryRequest<FetchMarketRequest, FetchMarketResponse>(`/${PolymarketService.typeName}/${method.name}`, (value: FetchMarketRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): FetchMarketResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Resolution checking
     *
     * @generated from protobuf rpc: CheckResolutions
     */
    checkResolutions(input: CheckResolutionsRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: CheckResolutionsResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: CheckResolutionsResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: CheckResolutionsResponse) => void)): grpc.ClientUnaryCall {
        const method = PolymarketService.methods[3];
        return this.makeUnaryRequest<CheckResolutionsRequest, CheckResolutionsResponse>(`/${PolymarketService.typeName}/${method.name}`, (value: CheckResolutionsRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): CheckResolutionsResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * Market tracking management
     *
     * @generated from protobuf rpc: AddTrackedMarket
     */
    addTrackedMarket(input: AddTrackedMarketRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: AddTrackedMarketResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: AddTrackedMarketResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: AddTrackedMarketResponse) => void)): grpc.ClientUnaryCall {
        const method = PolymarketService.methods[4];
        return this.makeUnaryRequest<AddTrackedMarketRequest, AddTrackedMarketResponse>(`/${PolymarketService.typeName}/${method.name}`, (value: AddTrackedMarketRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): AddTrackedMarketResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: RemoveTrackedMarket
     */
    removeTrackedMarket(input: RemoveTrackedMarketRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: RemoveTrackedMarketResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: RemoveTrackedMarketResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: RemoveTrackedMarketResponse) => void)): grpc.ClientUnaryCall {
        const method = PolymarketService.methods[5];
        return this.makeUnaryRequest<RemoveTrackedMarketRequest, RemoveTrackedMarketResponse>(`/${PolymarketService.typeName}/${method.name}`, (value: RemoveTrackedMarketRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): RemoveTrackedMarketResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
    /**
     * @generated from protobuf rpc: GetTrackedMarkets
     */
    getTrackedMarkets(input: GetTrackedMarketsRequest, metadata: grpc.Metadata | grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetTrackedMarketsResponse) => void), options?: grpc.CallOptions | ((err: grpc.ServiceError | null, value?: GetTrackedMarketsResponse) => void), callback?: ((err: grpc.ServiceError | null, value?: GetTrackedMarketsResponse) => void)): grpc.ClientUnaryCall {
        const method = PolymarketService.methods[6];
        return this.makeUnaryRequest<GetTrackedMarketsRequest, GetTrackedMarketsResponse>(`/${PolymarketService.typeName}/${method.name}`, (value: GetTrackedMarketsRequest): Buffer => Buffer.from(method.I.toBinary(value, this._binaryOptions)), (value: Buffer): GetTrackedMarketsResponse => method.O.fromBinary(value, this._binaryOptions), input, (metadata as any), (options as any), (callback as any));
    }
}
